(TeX-add-style-hook
 "jfm-instructions"
 (lambda ()
   (TeX-run-style-hooks
    "latex2e"
    "jfm"
    "jfm10"
    "graphicx"
    "epstopdf"
    "epsfig")
   (LaTeX-add-labels
    "sec:rules_submission"
    "sec:types_paper"
    "sec:filetypes"
    "fig:ka"
    "fig:kd"
    "tab:kd"
    "online"
    "notstyle"
    "appA"
    "Helm"
    "singular"
    "symbc"
    "inteqpt"
    "eq35"
    "defQc"
    "eq41"
    "eq42"
    "eq43")
   (LaTeX-add-environments
    "lemma"
    "corollary")
   (LaTeX-add-bibliographies))
 :latex)

